stages:
  - backend-build
#  - frontend-build
  - package
  - deploy

backend-build:
  stage: backend-build
  image: laravelsail/php81-composer:latest
  script:
#    - cp $VCD_ENV .env
    - composer install --ignore-platform-reqs
  cache:
    paths:
      - vendor
  artifacts:
    paths:
      - vendor
  tags:
    - vtcm-shared-docker-runner
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\@build/

#frontend-build:
#  stage: frontend-build
#  image: node:18.16.0
#  script:
#    - yarn
#    - yarn production
#  cache:
#    paths:
#      - node_modules
#  artifacts:
#    paths:
#      - public/vue-js
#      - public/mix-manifest.json
#  tags:
#    - vtcm-shared-docker-runner
#  only:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /\@build/

package:
  stage: package
  variables:
    IMAGE_TAG: northside:latest
  script:
    - docker login registry-gitlab.vtcmobile.vn -u $USERNAME -p $DEPLOY_KEY
    - docker build -f ./Dockerfile -t registry-gitlab.vtcmobile.vn/baclv/$IMAGE_TAG .
    - docker push registry-gitlab.vtcmobile.vn/baclv/$IMAGE_TAG
  tags:
    - vtcm-shared-shell-runner
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\@build/

deploy:
  stage: deploy
  script:
    - curl -X POST $DEV_DEPLOY_WEBHOOK
  tags:
    - vtcm-shared-shell-runner
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\@build/


